_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.10.8
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 50
                - 53
                - 55
                - 63
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 50
                - 53
                - 55
                - 63
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.8
            "5": 0.19.11
            "6": 4.51.3
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
batch_size:
    value: 16
epochs:
    value: 10
lr_backbone:
    value: 1e-05
lr_scratch:
    value: 0.0001
