wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.15.8
    framework: huggingface
    huggingface_version: 4.51.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1747000615.846139
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 50
      - 53
      - 55
      - 63
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 50
      - 53
      - 55
      - 63
      3:
      - 23
      4: 3.10.8
      5: 0.15.8
      6: 4.51.3
      8:
      - 5
